#[start runtime]
runtime: python
env: flex
#launch w/ gunicorn and migrate 
entrypoint: gunicorn -b :$PORT --chdir batproject/ batproject.wsgi && python3 batproject/manage.py migrate
beta_settings:
  cloud_sql_instances: sksys-bat:europe-west3:sksys-bat-instance
runtime_config:
  python_version: 3
# [END runtime]